version: "2"
services:
  web:
    build:
      context: ./backend
    environment:
      - DB_NAME=MR_PROD
    depends_on:
      - db
    ports:
      - 8000:8000
    command: python -m app.main
  db:
    image: "mongo"
    volumes:
      - ./mongodb:/data/db
    ports:
      - 27017:27017
