version: "2"
services:
  web:
    build:
      context: ./backend
    environment:
      - DB_NAME=MR_PROD
    depends_on:
      - db
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
  db:
    image: "mongo"
    volumes:
      - ./mongodb:/data/db
