version: "2"
services:
  backend:
    build:
      context: ./backend
    container_name: "backend"
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
